import Head from "next/head";
import Image from "next/image";
import img from "../public/background.jpg";
import { useFormik } from "formik";
import * as Yup from "yup";
import { useRouter } from "next/router";
import { motion as m } from "framer-motion";

export default function Home() {
  //router
  const router = useRouter();

  //formik logic
  const formik = useFormik({
    initialValues: {
      name: "",
      email: "",
      country: "United States",
      terms: "",
    },

    //validate form
    validationSchema: Yup.object({
      name: Yup.string()
        .max(20, "Name must be 20 characters or less")
        .required("Name is required"),
      email: Yup.string()
        .email("Invalid email address")
        .required("Email is required"),
      terms: Yup.array().required("Terms of service must be checked!"),
    }),

    //submit form
    onSubmit: (values) => {
      console.log(values);
      //query sends data through to the other page
      router.push({ pathname: "/success", query: values });
    },
  });

  // console.log(formik.values);
  console.log(formik.errors);

  return (
    <m.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      exit={{ opacity: 0 }}
      className="absolute w-full">
      <Head>
        <title>Forms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen flex items-center justify-center">
        <form
          onSubmit={formik.handleSubmit}
          className="bg-white flex rounded-lg w-1/2">
          <div className="flex-1 text-gray-700 p-20 w-1/2">
            <h1 className="text-3xl pb-2">Lets get started</h1>
            <p className="text-lg text-gray-500">
              Join our E-learning platform today and unlock over 500+ courses
              and digital assets ready to download.
            </p>
            <div className="mt-6">
              <div className="pb-4">
                <label
                  htmlFor="name"
                  className={`block text-sm pb-2 ${
                    formik.touched.name && formik.errors.name
                      ? "text-red-500"
                      : ""
                  }`}>
                  {formik.touched.name && formik.errors.name
                    ? formik.errors.name
                    : "Name:"}
                </label>
                <input
                  type="text"
                  name="name"
                  value={formik.values.name}
                  onChange={formik.handleChange}
                  onBlur={formik.handleBlur}
                  placeholder="Enter your name"
                  className="border-1 border-gray-500 p-2 rounded-md w-full focus:border-teal-50 focus:ring-teal-500"
                />
              </div>
            </div>
            <div className="pb-4">
              <label
                htmlFor="email"
                className={`block text-sm pb-2 ${
                  formik.touched.email && formik.errors.email
                    ? "text-red-500"
                    : ""
                }`}>
                {formik.touched.email && formik.errors.email
                  ? formik.errors.email
                  : "Email:"}
              </label>
              <input
                type="email"
                name="email"
                value={formik.values.email}
                onChange={formik.handleChange}
                onBlur={formik.handleBlur}
                placeholder="Enter your email"
                className="border-1 border-gray-500 p-2 rounded-md w-full focus:border-teal-50 focus:ring-teal-500"
              />
            </div>
            <div className="pb-4">
              <label htmlFor="email" className="block text-sm pb-2">
                Country
              </label>
              <select
                name="country"
                value={formik.values.country}
                onChange={formik.handleChange}
                className="border-1 border-gray-500 p-2 rounded-md w-full focus:border-teal-50 focus:ring-teal-500">
                <option>United States</option>
                <option>Mexico</option>
                <option>Germany</option>
                <option>Bahamas</option>
                <option>Jamaica</option>
              </select>
            </div>
            <div className="pb-4">
              <label
                htmlFor="terms"
                className={`block text-sm pb-2 ${
                  formik.touched.terms && formik.errors.terms
                    ? "text-red-500"
                    : ""
                }`}>
                {formik.touched.terms && formik.errors.terms
                  ? formik.errors.terms
                  : "Terms of service:"}
              </label>
              <div className="flex gap-2">
                <input
                  type="checkbox"
                  name="terms"
                  id="terms"
                  value="checked"
                  onChange={formik.handleChange}
                  className="h-5 w-5 text-teal-500 border-2 focus:border-teal-500 focus:ring-teal-50"
                />
                <p className="text-sm text-gray-500">
                  I agree to the Terms and Service that my data will be taken
                  and sold.
                </p>
              </div>
            </div>
            <button
              type="submit"
              className="bg-teal-500 bold text-sm text-white p-3 mt-6 rounded-lg w">
              Start Learning Today
            </button>
          </div>
          <div className="flex relative w-1/2">
            <Image
              alt="form-learn"
              src={img}
              priority
              fill="true"
              className="object-cover rounded-lg"
            />
          </div>
        </form>
      </main>
    </m.div>
  );
}
